<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>    
    <ApplicationIcon>Febris-icon.ico</ApplicationIcon>    
    <Configurations>Debug;Release;Staging</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Icons\fa-brands-400.ttf" />
    <EmbeddedResource Include="Resources\Icons\fa-regular-400.ttf" />
    <EmbeddedResource Include="Resources\Icons\fa-solid-900.ttf" />
    <EmbeddedResource Include="Resources\Images\DefaultPerson.png">
      <LogicalName>DefaultUser.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Images\Febris-Logo-recolored_white-gimp.png">
      <LogicalName>Logo.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Images\FebrisIcon_White.png">
      <LogicalName>LogoIcon.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="SkiaSharp" Version="2.80.3" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Febris.SharedMobileLibrary\Febris.SharedMobileLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MVVM\View\ConfigurationPage.xaml.cs">
      <DependentUpon>ConfigurationPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="MVVM\View\MessageBoardPage.xaml.cs">
      <DependentUpon>MessageBoardPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="MVVM\View\AboutPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\CompanionAppPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\ConfigurationPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\DeviceInfoModal.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\PairingModal.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\DeviceListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\DevicePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\LauncherPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\LocalFileRepositoryPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\MessageBoardPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\ModuleListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\PairingPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\ProfessionalInfo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\StatementFiles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\TestInfo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\UserListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MVVM\View\VideoStreamPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>